### ISSUE TITLE
Is it still alive of should we look at Foresti ?

### ISSUE THREAD

**Issue by charly37** [spotify/gcp-firewall-enforcer#1]
We have similar need and before having a look to deep on this project we wonder if it is still alive or if the FORESTI project replace this one ? We are wondering since we come across this article: https://cloudplatform.googleblog.com/2017/09/with-Forseti-Spotify-and-Google-release-GCP-security-tools-to-open-source-community15.html
Thx for clarification

**Comment by gbrindisi** [comment]
We currently use both `gcp-firewall-enforcer` and Forseti for different use cases.

But we look forward to switching everything to Forseti Enforcer as soon as it reach maturity and cover all our needs. 

If your use cases are covered I would suggest to lean towards Forseti.

**Comment by charly37** [comment]
Thx for your clarification (and for sharing your tools). We are going to start having a deeper look on Forseti.
